x = float(input("Enter the value for x: "))
y = float(input("Enter the value for y: "))

print("Arithmetic Operations on x and y:")
print("Addition  :", x + y)
print("Subtraction  :", x - y)
print("Multiplication  :", x * y)
print("Division  :", x / y)
print("Floor Division  :", x // y)
print("Modulus  :", x % y)
print("Exponentiation :", x ** y)
